# 数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
# 日志
logging:
  level:
    root: info
    cn.itcat: debug
  file: log/blog-dev.log
server:
  port: 9090
  servlet:
    context-path: /