spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false


comment.avatar: /img/user.jpg
comment.meavatar: /img/me.jpg


mybatis:
  configuration:
    cache-enabled: true